FROM ubuntu:17.10
RUN apt-get update && apt-get install -y --no-install-recommends \
  gcc \
  libc6-dev \
  file \
  make \
  ca-certificates \
  g++ \
  git \
  python \
  curl \
  bzip2 \
  perl \
  wget \
  autoconf \
  gettext
